// <auto-generated />
namespace SeoPoc.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _0002SiteInternalName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_0002SiteInternalName));
        
        string IMigrationMetadata.Id
        {
            get { return "201901090752550_0002-SiteInternalName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
